[package]
edition = "2021"
name = "mongo-peg-parser"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.0"
pest_derive = "2.0"
serde = "1"
serde_json = {version = "1", features = ["preserve_order"]}
