name: CI

# This workflow run tests and build for each push

on:
  push:
    branches:
      - main
      - "feature-**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
      - name: Test
        run: |
          cargo test
